In [10]:
# Dependencies
import json
import requests
import gmaps
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from config import weather_api_key
from config import gkey
from citipy import citipy

In [11]:
lat = []
lon = []
coords = []
data = []

coords_df = pd.DataFrame({'lat': (np.random.uniform(-0.9,0.9,500)*100), 'lon': (np.random.uniform(-1.8,1.8,500)*100)})
coords_df.head()

         lat         lon
0  -5.659195   98.074327
1  -2.986339 -176.618060
2 -58.433341 -113.003454
3 -29.486083 -126.626409
4 -17.932803   50.585759

In [13]:

cities = []
code = []
for i in range(0,len(coords_df['lat'])):
    lat=coords_df.iloc[i]['lat']
    lon=coords_df.iloc[i]["lon"]
    city=citipy.nearest_city(lat,lon)
    name=city.city_name
    cities.append(name)
    country=city.country_code
    code.append(country)
    
coords_df['City']=cities
coords_df['Country']=code
coords_df.head()

# Drop duplicate cities
coords_df.drop_duplicates("City", keep='first').reset_index(drop = True, inplace=True)

print(f"There are {len(coords_df)} cities left after dropping all duplicate values")

coords_df.head()

There are 500 cities left after dropping all duplicate values

         lat         lon           City Country
0  -5.659195   98.074327       bengkulu      id
1  -2.986339 -176.618060        vaitupu      wf
2 -58.433341 -113.003454        rikitea      pf
3 -29.486083 -126.626409        rikitea      pf
4 -17.932803   50.585759  ambodifototra      mg

In [15]:
# Adding Temperature , Humidity, Cloud Cover, Wind Speed and Date to the data framecoords_df.loc[:, "Max Temp"] = ""
coords_df.loc[:, "Max Temp"] = ""
coords_df.loc[:, "Humidity"] = ""
coords_df.loc[:, "Cloud Cover"] = ""
coords_df.loc[:, "Wind Speed"] = ""
coords_df.loc[:, "Date"] = ""
coords_df.head()

,lat,lon,City,Country,Max Temp,Humidity,Cloud Cover,Wind Speed,Date
0,-5.659195,98.074327,bengkulu,id,,,,,
1,-2.986339,-176.618060,vaitupu,wf,,,,,
2,-58.433341,-113.003454,rikitea,pf,,,,,
3,-29.486083,-126.626409,rikitea,pf,,,,,
4,-17.932803,50.585759,ambodifototra,mg,,,,,

In [23]:
# Loop through the cities_pd and run a weather search for each city
# url = "http://api.openweathermap.org/data/2.5/weather?"
# query_url = url + "appid=" + weather_api_key + "&q="
mylist = coords_df['City']
for row in mylist:
    
    # query_url = url + "appid=" + weather_api_key + "&q="
    
    query_url="http://api.openweathermap.org/data/2.5/weather?q=%s&units=IMPERIAL&mode=json&APPID=%s" % (row.replace(" ","+"), weather_api_key)
    weather_data = requests.get(query_url).json()
    
    coords_df['Max Temp'] = weather_data['main']['temp_max']
    coords_df.at[:, 'Humidity'] = weather_data['main']['humidity']
    coords_df.at[:, 'Cloud Cover'] = weather_data['clouds']['all']
    coords_df.at[:, 'Wind Speed'] = weather_data['wind']['speed']
    coords_df.at[:, 'Date'] = weather_data['dt']
    
    # cities_coords.set_value(index, "Max Temp", weather_data["main"]["temp_max"])
    # cities_coords.at(index, "Humidity", weather_data["main"]["humidity"])
    # cities_coords.at(index, "Cloud Cover", weather_data["clouds"]["all"])
    # cities_coords.at(index, "Wind Speed", weather_data["wind"]["speed"])
    
    
    # print(weather_data)    
    # print(f"Data Retrieval Initialized...")
    # print(f".............................")
    # print(f"Retrieving Record {index + 1} of Set 1 | {city['City']}")
    

    # try:
        # wet_1 = weather_data[0]["main"]["temp_max"]
        # wet_2 = weather_data["main"]["humidity"]
        # wet_3 = weather_data["clouds"]["all"]
        # wet_4 = weather_data["wind"]["speed"]
        # wet_5 = weather_data["dt"]
    # except:
        # zee = "There is no weather data for city....."                                                             
    
                    
# Turn columns to numeric because of empty rows
# cities_coords["Max Temp"] = pd.to_numeric(cities_coords["Max Temp"], errors='coerce')
# cities_coords["Humidity"] = pd.to_numeric(cities_coords["Humidity"], errors='coerce')
# cities_coords["Cloud Cover"] = pd.to_numeric(cities_coords["Cloud Cover"], errors='coerce')
# cities_coords["Wind Speed"] = pd.to_numeric(cities_coords["Wind Speed"], errors='coerce')

coords_df.head()

KeyError: 'main'

In [ ]:
city_name = []
lat = []
long = []
temp = []
hum = []
wind_sp = []
cloudy = []
country = []
dt = []

# Save config information.
url = "http://api.openweathermap.org/data/2.5/weather?"
mix = ['burundi', 'freetown', 'accra']

# Build partial query URL

query_url = url + "appid=" + weather_api_key + "&q=" 

for point in new_pts:
    # Look for city using coordinates(lat,long)
    city = citipy.nearest_city(point[0], point[1])
    # City Name
    cities.append(city.city_name)
    # cities_for_weather = list(cities)
    print(cities)

for city in city_list:
    
    
       
    
    response = requests.get(query_url + city)
    weather = response.json()
    
   
    
    
    
    print(f"Data Retrieval Initialized...")
    print(f".............................")
    print(f"Retrieving Record {i + 1} of Set 1 | {city}")
    
    
    # weather = json.dumps(weather_json, indent=4, sort_keys=True)
    # json.dumps(weather_json, indent=4, sort_keys=True)
    
     
    city_name=weather['name']
    lat=weather['coord']['lat']
    long=weather['coord']['lon']
    temp=weather['main']['temp_max']
    hum=weather['main']['humidity']
    wind_sp=weather['main']['humidity']
    cloudy=weather['wind']['speed']
    country=weather['sys']['country']
    dt=weather['dt']
    
    data.append((city_name, lat, long, temp, hum, wind_sp, cloudy, country, dt))
cols = ['City', 'Latitude', 'Longitude', 'Max Temp', 'Humidty', 'Wind Speed', 'Cloudiness', 'Country', 'Date']
        
    
    
weather_df = pd.DataFrame(data, columns=cols)
weather_df.to_csv('weather_cities.csv', encoding='utf-8')

In [ ]:
url = "http://api.openweathermap.org/data/2.5/weather?"
query_url = url + "appid=" + weather_api_key + "&q="

for city in enumerate(cities_coords['City']):
    
    query_url = url + "appid=" + weather_api_key + "&q="
    
        # query_url="http://api.openweathermap.org/data/2.5/weather?q=%s&units=IMPERIAL&mode=json&APPID=%s" % (row["City"].replace(" ","+"), weather_api_key)
    weather_data = requests.get(query_url + city[1]).json()
    
    # print(weather_data)    
    # print(f"Data Retrieval Initialized...")
    # print(f".............................")
    # print(f"Retrieving Record {index + 1} of Set 1 | {city['City']}")
    

    try:
        temp=weather_data['main']['temp_max']
        hum=weather_data['main']['humidity']
        wind_sp=weather_data['main']['humidity']
        cloudy=weather_data['wind']['speed']
        country=weather_data['sys']['country']
        dt=weather_data['dt']
        
        data.append((city_name, lat, long, temp, hum, wind_sp, cloudy, country, dt))

        
    
    

    except:
        print("There is no weather data for city.....")  
cols = ['City', 'Latitude', 'Longitude', 'Max Temp', 'Humidty', 'Wind Speed', 'Cloudiness', 'Country', 'Date']
weather_df = pd.DataFrame(data, columns=cols)
weather_df.head()

In [ ]:
    temp=weather['main']['temp_max']
    hum=weather['main']['humidity']
    wind_sp=weather['main']['humidity']
    cloudy=weather['wind']['speed']
    country=weather['sys']['country']
    dt=weather['dt']
    
    data.append((city_name, lat, long, temp, hum, wind_sp, cloudy, country, dt))
cols = ['City', 'Latitude', 'Longitude', 'Max Temp', 'Humidty', 'Wind Speed', 'Cloudiness', 'Country', 'Date']
        
    
    
weather_df = pd.DataFrame(data, columns=cols)
weather_df.to_csv('weather_cities.csv', encoding='utf-8')

In [ ]:
 try:
        cities_coords.set_value(index, "Max Temp", weather_data["main"]["temp_max"])
        cities_coords.set_value(index, "Humidity", weather_data["main"]["humidity"])
        cities_coords.set_value(index, "Cloud Cover", weather_data["clouds"]["all"])
        cities_coords.set_value(index, "Wind Speed", weather_data["wind"]["speed"])
        cities_coords.set_value(index, "Date", weather_data["dt"])
    except:
        print("There is no weather data for city.....")                                                               
    
                    
# Turn columns to numeric because of empty rows
cities_coords["Max Temp"] = pd.to_numeric(cities_coords["Max Temp"], errors='coerce')
cities_coords["Humidity"] = pd.to_numeric(cities_coords["Humidity"], errors='coerce')
cities_coords["Cloud Cover"] = pd.to_numeric(cities_coords["Cloud Cover"], errors='coerce')
cities_coords["Wind Speed"] = pd.to_numeric(cities_coords["Wind Speed"], errors='coerce')

cities_coords.head()